-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-14 19:08:50 CLST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE BOLETA 
    ( 
     numero_boleta        NUMBER (10)  NOT NULL , 
     fecha_venta          DATE  NOT NULL , 
     cantidad_productos   NUMBER (6)  NOT NULL , 
     monto_total          NUMBER (12,2)  NOT NULL , 
     CLIENTE_rut_cliente  NUMBER (8)  NOT NULL , 
     SUCURSAL_id_sucursal NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE BOLETA 
    ADD CONSTRAINT BOLETA_PK PRIMARY KEY ( numero_boleta ) ;

CREATE TABLE CATEGORIA 
    ( 
     id_categoria     NUMBER (3)  NOT NULL , 
     nombre_categoria VARCHAR2 (50)  NOT NULL , 
     vence            CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE CATEGORIA 
    ADD CONSTRAINT CATEGORIA_PK PRIMARY KEY ( id_categoria ) ;

CREATE TABLE CLIENTE 
    ( 
     rut_cliente      NUMBER (8)  NOT NULL , 
     dv_cliente       CHAR (1)  NOT NULL , 
     primer_nombre    VARCHAR2 (60)  NOT NULL , 
     segundo_nombre   VARCHAR2 (60) , 
     apellido_paterno VARCHAR2 (60)  NOT NULL , 
     apellido_materno VARCHAR2 (60)  NOT NULL , 
     telefono_cliente VARCHAR2 (15) , 
     email_cliente    VARCHAR2 (80) 
    ) 
;

ALTER TABLE CLIENTE 
    ADD CONSTRAINT CLIENTE_PK PRIMARY KEY ( rut_cliente ) ;

CREATE TABLE COMUNA 
    ( 
     id_comuna        NUMBER (3)  NOT NULL , 
     nombre_comuna    VARCHAR2 (60)  NOT NULL , 
     REGION_id_region NUMBER (2)  NOT NULL 
    ) 
;

ALTER TABLE COMUNA 
    ADD CONSTRAINT COMUNA_PK PRIMARY KEY ( id_comuna ) ;

CREATE TABLE DETALLE_BOLETA 
    ( 
     BOLETA_numero_boleta NUMBER (10)  NOT NULL , 
     PRODUCTO_id_producto NUMBER (5)  NOT NULL , 
     PRODUCTO_id_sucursal NUMBER (3)  NOT NULL , 
     cantidad             NUMBER (5)  NOT NULL , 
     precio_unitario      NUMBER (10,2)  NOT NULL 
    ) 
;

ALTER TABLE DETALLE_BOLETA 
    ADD CONSTRAINT DETALLE_BOLETA_PK PRIMARY KEY ( BOLETA_numero_boleta, PRODUCTO_id_producto, PRODUCTO_id_sucursal ) ;

CREATE TABLE MARCA 
    ( 
     id_marca     NUMBER (4)  NOT NULL , 
     nombre_marca VARCHAR2 (60)  NOT NULL 
    ) 
;

ALTER TABLE MARCA 
    ADD CONSTRAINT MARCA_PK PRIMARY KEY ( id_marca ) ;

CREATE TABLE MODELO 
    ( 
     id_modelo      NUMBER (4)  NOT NULL , 
     nombre_modelo  VARCHAR2 (70)  NOT NULL , 
     MARCA_id_marca NUMBER (4)  NOT NULL 
    ) 
;

ALTER TABLE MODELO 
    ADD CONSTRAINT MODELO_PK PRIMARY KEY ( id_modelo, MARCA_id_marca ) ;

CREATE TABLE PRODUCTO 
    ( 
     id_producto             NUMBER (5)  NOT NULL , 
     fecha_vencimiento       DATE , 
     valor                   NUMBER (10,2)  NOT NULL , 
     SUCURSAL_id_sucursal    NUMBER (3)  NOT NULL , 
     PROVEEDOR_rut_proveedor NUMBER (8)  NOT NULL , 
     CATEGORIA_id_categoria  NUMBER (3)  NOT NULL , 
     MODELO_id_modelo        NUMBER (4)  NOT NULL , 
     MODELO_MARCA_id_marca   NUMBER (4)  NOT NULL 
    ) 
;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_PK PRIMARY KEY ( id_producto, SUCURSAL_id_sucursal ) ;

CREATE TABLE PROVEEDOR 
    ( 
     rut_proveedor      NUMBER (8)  NOT NULL , 
     dv_proveedor       CHAR (1)  NOT NULL , 
     tipo_proveedor     CHAR (1)  NOT NULL , 
     telefono_proveedor VARCHAR2 (15)  NOT NULL , 
     email_proveedor    VARCHAR2 (80)  NOT NULL , 
     nombre_calle       VARCHAR2 (30)  NOT NULL , 
     numero_calle       NUMBER (5)  NOT NULL , 
     depto              VARCHAR2 (10) 
    ) 
;

ALTER TABLE PROVEEDOR 
    ADD CONSTRAINT PROVEEDOR_PK PRIMARY KEY ( rut_proveedor ) ;

CREATE TABLE PROVEEDOR_EMPRESA 
    ( 
     PROVEEDOR_rut_proveedor NUMBER (8)  NOT NULL , 
     razon_social            VARCHAR2 (80)  NOT NULL , 
     sitio_web               VARCHAR2 (100) 
    ) 
;

ALTER TABLE PROVEEDOR_EMPRESA 
    ADD CONSTRAINT PROVEEDOR_EMPRESA_PK PRIMARY KEY ( PROVEEDOR_rut_proveedor ) ;

CREATE TABLE PROVEEDOR_PERSONA 
    ( 
     PROVEEDOR_rut_proveedor NUMBER (8)  NOT NULL , 
     primer_nombre           VARCHAR2 (60)  NOT NULL , 
     segundo_nombre          VARCHAR2 (60) , 
     apellido_paterno        VARCHAR2 (60)  NOT NULL , 
     apellido_materno        VARCHAR2 (60)  NOT NULL 
    ) 
;

ALTER TABLE PROVEEDOR_PERSONA 
    ADD CONSTRAINT PROVEEDOR_PERSONA_PK PRIMARY KEY ( PROVEEDOR_rut_proveedor ) ;

CREATE TABLE REGION 
    ( 
     id_region     NUMBER (2)  NOT NULL , 
     nombre_region VARCHAR2 (50)  NOT NULL 
    ) 
;

ALTER TABLE REGION 
    ADD CONSTRAINT REGION_PK PRIMARY KEY ( id_region ) ;

CREATE TABLE SUCURSAL 
    ( 
     id_sucursal        NUMBER (3)  NOT NULL , 
     nombre_sucursal    VARCHAR2 (60)  NOT NULL , 
     direccion_sucursal VARCHAR2 (100)  NOT NULL , 
     COMUNA_id_comuna   NUMBER (3)  NOT NULL 
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT SUCURSAL_PK PRIMARY KEY ( id_sucursal ) ;

ALTER TABLE BOLETA 
    ADD CONSTRAINT BOLETA_CLIENTE_FK FOREIGN KEY 
    ( 
     CLIENTE_rut_cliente
    ) 
    REFERENCES CLIENTE 
    ( 
     rut_cliente
    ) 
;

ALTER TABLE BOLETA 
    ADD CONSTRAINT BOLETA_SUCURSAL_FK FOREIGN KEY 
    ( 
     SUCURSAL_id_sucursal
    ) 
    REFERENCES SUCURSAL 
    ( 
     id_sucursal
    ) 
;

ALTER TABLE COMUNA 
    ADD CONSTRAINT COMUNA_REGION_FK FOREIGN KEY 
    ( 
     REGION_id_region
    ) 
    REFERENCES REGION 
    ( 
     id_region
    ) 
;

ALTER TABLE DETALLE_BOLETA 
    ADD CONSTRAINT DETALLE_BOLETA_BOLETA_FK FOREIGN KEY 
    ( 
     BOLETA_numero_boleta
    ) 
    REFERENCES BOLETA 
    ( 
     numero_boleta
    ) 
;

ALTER TABLE DETALLE_BOLETA 
    ADD CONSTRAINT DETALLE_BOLETA_PRODUCTO_FK FOREIGN KEY 
    ( 
     PRODUCTO_id_producto,
     PRODUCTO_id_sucursal
    ) 
    REFERENCES PRODUCTO 
    ( 
     id_producto,
     SUCURSAL_id_sucursal
    ) 
;

ALTER TABLE MODELO 
    ADD CONSTRAINT MODELO_MARCA_FK FOREIGN KEY 
    ( 
     MARCA_id_marca
    ) 
    REFERENCES MARCA 
    ( 
     id_marca
    ) 
;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_CATEGORIA_FK FOREIGN KEY 
    ( 
     CATEGORIA_id_categoria
    ) 
    REFERENCES CATEGORIA 
    ( 
     id_categoria
    ) 
;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_MODELO_FK FOREIGN KEY 
    ( 
     MODELO_id_modelo,
     MODELO_MARCA_id_marca
    ) 
    REFERENCES MODELO 
    ( 
     id_modelo,
     MARCA_id_marca
    ) 
;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_rut_proveedor
    ) 
    REFERENCES PROVEEDOR 
    ( 
     rut_proveedor
    ) 
;

ALTER TABLE PRODUCTO 
    ADD CONSTRAINT PRODUCTO_SUCURSAL_FK FOREIGN KEY 
    ( 
     SUCURSAL_id_sucursal
    ) 
    REFERENCES SUCURSAL 
    ( 
     id_sucursal
    ) 
;

ALTER TABLE PROVEEDOR_EMPRESA 
    ADD CONSTRAINT PROVEEDOR_EMPRESA_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_rut_proveedor
    ) 
    REFERENCES PROVEEDOR 
    ( 
     rut_proveedor
    ) 
;

ALTER TABLE PROVEEDOR_PERSONA 
    ADD CONSTRAINT PROVEEDOR_PERSONA_PROVEEDOR_FK FOREIGN KEY 
    ( 
     PROVEEDOR_rut_proveedor
    ) 
    REFERENCES PROVEEDOR 
    ( 
     rut_proveedor
    ) 
;

ALTER TABLE SUCURSAL 
    ADD CONSTRAINT SUCURSAL_COMUNA_FK FOREIGN KEY 
    ( 
     COMUNA_id_comuna
    ) 
    REFERENCES COMUNA 
    ( 
     id_comuna
    ) 
;

CREATE OR REPLACE TRIGGER ARC_Arc_1_PROVEEDOR_PERSONA 
BEFORE INSERT OR UPDATE OF PROVEEDOR_rut_proveedor 
ON PROVEEDOR_PERSONA 
FOR EACH ROW 
DECLARE 
    d CHAR (1); 
BEGIN 
    SELECT A.tipo_proveedor INTO d 
    FROM PROVEEDOR A 
    WHERE A.rut_proveedor = :new.PROVEEDOR_rut_proveedor; 
    IF (d IS NULL OR d <> 'P') THEN 
        raise_application_error(-20223,'FK PROVEEDOR_PERSONA_PROVEEDOR_FK in Table PROVEEDOR_PERSONA violates Arc constraint on Table PROVEEDOR - discriminator column tipo_proveedor doesn''t have value ''P'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/

CREATE OR REPLACE TRIGGER ARC_Arc_1_PROVEEDOR_EMPRESA 
BEFORE INSERT OR UPDATE OF PROVEEDOR_rut_proveedor 
ON PROVEEDOR_EMPRESA 
FOR EACH ROW 
DECLARE 
    d CHAR (1); 
BEGIN 
    SELECT A.tipo_proveedor INTO d 
    FROM PROVEEDOR A 
    WHERE A.rut_proveedor = :new.PROVEEDOR_rut_proveedor; 
    IF (d IS NULL OR d <> 'E') THEN 
        raise_application_error(-20223,'FK PROVEEDOR_EMPRESA_PROVEEDOR_FK in Table PROVEEDOR_EMPRESA violates Arc constraint on Table PROVEEDOR - discriminator column tipo_proveedor doesn''t have value ''E'''); 
    END IF; 
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
        NULL; 
    WHEN OTHERS THEN 
        RAISE; 
END; 
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           2
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
